### ISSUE TITLE
Failed in generate report and plot

### ISSUE THREAD

**Issue by fuyang2032** [BrechtDeMan/WebAudioEvaluationTool#215]
Hi, I just run into the following issues when running generate_report.py. Highly appreciate for any support to tackle this problem.

Use: python generate_report.py [results_folder] [no_render | -nr]
Using default path: ../saves/
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**timeline_view_movement.py**", line 120, in <module>
    final_position = float(audioelement.find("./value").text)
**ValueError: could not convert string to float: false**
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**score_plot.py**", line 148, in <module>
    plt.boxplot(ratings)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 2710, in boxplot
    manage_xticks=manage_xticks, data=data)
  File "/usr/lib/python2.7/dist-packages/matplotlib/__init__.py", line 1814, in inner
    return func(ax, *args, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_axes.py", line 3212, in boxplot
    labels=labels)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 1980, in boxplot_stats
    X = _reshape_2D(X)
  File "/usr/lib/python2.7/dist-packages/matplotlib/cbook.py", line 2248, in _reshape_2D
    X = [np.ravel(x) for x in X]
  File "/usr/lib/python2.7/dist-packages/numpy/core/fromnumeric.py", line 1487, in ravel
    return asanyarray(a).ravel(order)
  File "/usr/lib/python2.7/dist-packages/numpy/core/numeric.py", line 533, in asanyarray
    return array(a, dtype, copy=False, order=order, subok=True)
**ValueError: Setting void-array with object members using buffer.**
Traceback (most recent call last):
  File "**generate_report.py**", line 264, in <module>
    not_moved[0]+'\\\\ \n'
**TypeError: cannot concatenate 'str' and 'NoneType' objects**

And the following modules have been tested to run correctly:

timeline_view.py (Pass)
score_parser.py (Pass)
evaluation_stats.py (Pass)
commentquestion_parser.py (Pass)
comment_parser (Pass)

**Comment by nickjillings** [comment]
Is this for an AB/X test yes? Just want to confirm as if it is then it's a simple fix.

**Comment by fuyang2032** [comment]
Thanks for your support nick. Yes, the above information corresponds to ABX test. I also tried generate_report.py with some other tests but it seems not to work properly.

**AB test (Fail):**
Use: python generate_report.py [results_folder] [no_render | -nr]
Using default path: ../saves/
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**timeline_view_movement.py**", line 302, in <module>
    scalelabels = scales[0].findall("./scalelabel") # get first scale by default
**IndexError: list index out of range**
Traceback (most recent call last):
  File "generate_report.py", line 252, in <module>
    ', '.join(not_played)+'\\\\ \n'
**TypeError: sequence item 0: expected string, NoneType found**

**MUSHRA (Fail):**
Use: python generate_report.py [results_folder] [no_render | -nr]
Using default path: ../saves/
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**timeline_view_movement.py**", line 120, in <module>
    final_position = float(audioelement.find("./value").text)
**AttributeError: 'NoneType' object has no attribute 'text'**
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**score_parser.py**", line 90, in <module>
    axisStore = storage[page_name]['axis'][axisName]
**KeyError: 'default'**
Traceback (most recent call last):
  File "**generate_report.py**", line 264, in <module>
    not_moved[0]+'\\\\ \n'
**TypeError: cannot concatenate 'str' and 'NoneType' objects**

**horizontal (Fail):**
Use: python generate_report.py [results_folder] [no_render | -nr]
Using default path: ../saves/
Traceback (most recent call last):
  File "**generate_report.py**", line 670, in <module>
    proc=subprocess.Popen(shlex.split('pdflatex -output-directory="'+folder_name+'" "'+ folder_name + 'Report.tex"'))
  File "/usr/lib/python2.7/**subprocess.py**", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/**subprocess.py**", line 1343, in _execute_child
    raise child_exception
**OSError: [Errno 2] No such file or directory**

**ordinal (Fail):**
Use: python generate_report.py [results_folder] [no_render | -nr]
Using default path: ../saves/
Traceback (most recent call last):
  File "/home/yf852/Downloads/WebAudioEvaluationTool-Dev2/python/**timeline_view_movement.py**", line 118, in <module>
    initial_position = float(initial_position_temp.text)
**TypeError: float() argument must be a string or a number**
/usr/lib/python2.7/dist-packages/numpy/lib/**function_base.py**:3823: RuntimeWarning: Invalid value encountered in percentile
  RuntimeWarning)
Traceback (most recent call last):
  File "**generate_report.py**", line 261, in <module>
    ', '.join(not_moved)+'\\\\ \n'
**TypeError: sequence item 0: expected string, NoneType found**

**Comment by nickjillings** [comment]
These should be fixed now in Dev_main (9c9b67e)

**Comment by fuyang2032** [comment]
Brilliant nick! These are fixed now. 

However, I still cannot generate a report as the following issues (using the data of a MUSHRA test):

Use: python **score_parser.py** [rating_folder_location]
Using default path: ../saves
Traceback (most recent call last):
  File "score_parser.py", line 92, in <module>
    axisStore = storage[page_name]['axis'][axisName]
KeyError: 'default'

Traceback (most recent call last):
  File "**generate_report.py**", line 671, in <module>
    proc=subprocess.Popen(shlex.split('pdflatex -output-directory="'+folder_name+'" "'+ folder_name + 'Report.tex"'))
  File "/usr/lib/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1343, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory

Thanks for your attention on the new issues!

**Comment by nickjillings** [comment]
The latest commit on Dev_main should now resolve the issue

**Comment by fuyang2032** [comment]
Unfortunately, it still does not work:

  File "score_parser.py", line 91, in <module>
    axisStore = storage[page_name]['axis'][axisName]
KeyError: 'default'

**Comment by nickjillings** [comment]
Are these with tests results created using the example configurations?

**Comment by fuyang2032** [comment]
Yes, when using mushra_example.xml

**Comment by nickjillings** [comment]
So now it should be working. It is actually a failure in the mushra.js propagating through to the final exception in score_parser.py. Essentially, you can give a friendly name for the interfaces / axis on each page. However only APE is multi-dimensional. But the score_parser looks for these pages and then creates them.

Now the problem is that the MUSHRA interface ignores this tag and doesn't place them in the final saves, but the score_parser looks at the embedded configuration file. So in short, it finds an axis on `test-1` called `preference`. Then it looks for the nodes which should read:
```xml
<value interface-name="preference">xxx</value>
```
but are actually just simple nodes. It then does not have a prepared store and throws the key error!

Now I've hacked the score_parser to always create a default store and place unlabelled stores within. For all tests this will be fine, since only APE is multi-dimensional and it throws an error when an axis is not correctly labelled. However some work to mushra.js must be made to correctly label the `value` nodes.

**Comment by fuyang2032** [comment]
Thanks nick, got the idea.
