### ISSUE TITLE
Playback hiccup

### ISSUE THREAD

**Issue by BrechtDeMan** [BrechtDeMan/WebAudioEvaluationTool#24]
Sometimes when first clicking a sample to play, it becomes red but there's silence; clicking another sample starts the audio - though not from the start (if samples are in sync that is), the song was 'playing' but not audible. 

Safari 8, Mac OS X.10

**Comment by BrechtDeMan** [comment]
(Still an issue at the time of latest commit)

**Comment by nickjillings** [comment]
Can you confirm if this bug is still active?

**Comment by BrechtDeMan** [comment]
Not as of right now - I've certainly experienced this very recently but it's quite random so I can't say for sure whether it's gone. I'll comment here (or reopen if you want to get rid of it) as soon as it happens again.

**Comment by BrechtDeMan** [comment]
Just experienced it again in both Safari and Chrome, in two sessions I had running at the same time. I made a video if you don't believe me!
Still no idea why this would happen.

**Comment by nickjillings** [comment]
@BrechtDeMan With all the issues with Chrome and #154, can you see if the two were related and perhaps have now been fixed with this?

The issues with Safar are more worrying for me as I've not been able to replicate them.

I have had issues where the audio context crashes, usually caused by the debugger being open causing some lock up, but whenever it is left alone it seems to work fine.

**Comment by BrechtDeMan** [comment]
As mentioned in #154, still an issue after 2bf0c23. 
Not noticed in Safari this time around.

**Comment by nickjillings** [comment]
OK, I'll close this then as this is most likely the #154 bug.
